name: slide_countdown
description: A Flutter package to create easy slide animation countdown / countup timer.
version: 0.0.6-dev.2
homepage: https://github.com/farhanfadila1717/slide_countdown
maintener: Farhan Fadila (@farhanfadila1717)

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  stream_duration: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
